name: Build Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cancel_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: t-actions/cancel-actions@master

  param:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.param.outputs.ref }}
      tag: ${{ steps.param.outputs.tag }}
      images: ${{ steps.images.outputs.images }}
    steps:
      - id: param
        uses: t-actions/calc-release@master
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.param.outputs.ref }}
      - id: images
        run: |
          IMAGES=$(python -c "import os, json; print(json.dumps(os.listdir('images')));")
          echo "::set-output name=images::$IMAGES"

  docker-build:
    needs: param
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.param.outputs.images) }}
        platform: [linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64, linux/ppc64le]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.param.outputs.ref }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: images/${{ matrix.image }}
          file: images/${{ matrix.image }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:${{ needs.param.outputs.tag }}